name: Python Script Workflow 

on: 
  push:
    branches:
      - main

jobs:
  run_python_script:
    name: Run faltu.py
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
 
    - name: Run faltu.py
      run: python faltu.py
  run_python_script_2:
    needs: run_python_script
    name: Run boring.py 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' # Use the Python version you need

    - name: Run Boring.py 
      run: python Boring.py
