name: Python Script Workflow 

on: 
  push:
    branches:
      - main

jobs:
  run_python_script:
    name: Run faltu.py
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Run faltu.py
      run: python faltu.py
